Add error checking to omnibus run and exit 1 on error

diff --git a/Dockerfile-ubuntu b/Dockerfile-ubuntu
--- a/Dockerfile-ubuntu
+++ b/Dockerfile-ubuntu
@@ -72,7 +72,12 @@ RUN useradd -m coopr && \
   chown -R coopr /opt && \
   su coopr -c "bundle install --binstubs" && \
   su coopr -c "git config --global user.email 'ops@cask.co' && git config --global user.name 'Cask Ops'" && \
-  for project in ${COOPR_BUILD_PROJECTS} ; do \
-    su coopr -c "bin/omnibus build ${project}" ; \
+  __failed= && \
+  for project in ${COOPR_BUILD_PROJECTS}; do \
+    su coopr -c "bin/omnibus build ${project}" || __failed+="${project} "; \
     rm -rf /opt/coopr ; \
-  done
+  done && \
+  if [[ -n ${__failed} ]]; then \
+    echo "ERROR: Failed to build ${__failed}"; \
+    exit 1; \
+  fi
